Vagrant.configure(2) do |config|
    config.ssh.insert_key = false 
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true
    config.hostmanager.manage_host = false
    config.vm.define "node1" do |node1|
      node1.vm.box = "generic/centos7" 
      node1.vm.synced_folder "./", "/vagrant"
      node1.vm.synced_folder "../../..", "/usr/src/git_repo"
      node1.vm.network "private_network", ip: "192.168.199.2"
      node1.vm.hostname = "node1.example.com"
      node1.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      node1.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      node1.vm.provision "shell", inline: "sudo yum install -y dos2unix"
      node1.vm.provision "shell", inline: "find /usr/src/git_repo/labs/02-Provision_the_environment/Vagrant/scripts -type f -print0 | xargs -0 dos2unix"
      node1.vm.provision "shell", path: "scripts/install_ambari_server.sh"
      node1.vm.provision "shell", path: "scripts/link_repo_to_vagrant_user.sh"
      node1.vm.provision "shell", path: "scripts/install_pig_0.17.sh"
      node1.vm.provision "shell", path: "scripts/install_maven.sh"
      node1.vm.provision "shell", path: "scripts/setup_mysql.sh"
      node1.vm.provision "shell", path: "scripts/install_nifi.sh"
      node1.vm.provision "shell", path: "scripts/install_mosquitto.sh"
      node1.vm.network "forwarded_port", guest: 8080, host: 8080
      node1.vm.network "forwarded_port", guest: 8090, host: 8090
      node1.vm.network "forwarded_port", guest: 3306, host: 3306
      node1.vm.network "forwarded_port", guest: 50070, host: 50070
      node1.vm.network "forwarded_port", guest: 8088, host: 8088
      node1.vm.network "forwarded_port", guest: 8020, host: 8020
      node1.vm.provider "virtualbox" do |v|
        v.memory = 5120
        #v.memory = 6144
        v.cpus = 2
        v.customize ['modifyvm', :id, '--cableconnected1', 'on']
        v.name = "hdp_node1"
      end
      node1.vm.provider :libvirt do |libvirt|
        libvirt.memory = 6144
      end
    end
    config.vm.define "node2" do |node2|
      node2.vm.box = "generic/centos7"
      node2.vm.synced_folder "./", "/vagrant"
      node2.vm.network "private_network", ip: "192.168.199.3"
      node2.vm.hostname = "node2.example.com"
      node2.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      node2.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      node2.vm.provision "shell", inline: "sudo yum install -y dos2unix"
      node2.vm.provision "shell", inline: "find /usr/src/git_repo/labs/02-Provision_the_environment/Vagrant/scripts -type f -print0 | xargs -0 dos2unix"
      node2.vm.provision "shell", path: "scripts/install_ambari_agent.sh"
      node2.vm.provider "virtualbox" do |v|
        v.memory = 2048
        #v.memory = 3072
        v.cpus = 2
        v.customize ['modifyvm', :id, '--cableconnected1', 'on']
        v.name = "hdp_node2"
      end
      node2.vm.provider :libvirt do |libvirt|
        libvirt.memory = 3072
      end
    end
    config.vm.define "node3" do |node3|
      node3.vm.box = "generic/centos7"
      node3.vm.synced_folder "./", "/vagrant"
      node3.vm.network "private_network", ip: "192.168.199.4"
      node3.vm.hostname = "node3.example.com"
      node3.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      node3.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      node3.vm.provision "shell", inline: "sudo yum install -y dos2unix"
      node3.vm.provision "shell", inline: "find /usr/src/git_repo/labs/02-Provision_the_environment/Vagrant/scripts -type f -print0 | xargs -0 dos2unix"
      node3.vm.provision "shell", path: "scripts/install_ambari_agent.sh"
      node3.vm.provision "shell", path: "scripts/create_cluster.sh"
      #node3.vm.provision "shell", inline: "sleep 300"
      #node3.vm.provision "shell", path: "scripts/add_vagrant_user_to_ambari.sh"
      node3.vm.provider "virtualbox" do |v|
        v.memory = 2048
        #v.memory = 3072
        v.cpus = 2
        v.customize ['modifyvm', :id, '--cableconnected1', 'on']
        v.name = "hdp_node3"
      end
      node3.vm.provider :libvirt do |libvirt|
        libvirt.memory = 3072
      end
    end
  end
