Vagrant.configure(2) do |config|
    config.ssh.insert_key = false 
    config.hostmanager.enabled = true
    config.hostmanager.manage_guest = true
    config.hostmanager.manage_host = false
    config.vm.define "node1" do |node1|
      node1.vm.box = "generic/centos7" 
      node1.vm.synced_folder ".", "/vagrant"
      node1.vm.synced_folder "../../..", "/usr/src/git_repo"
      node1.vm.network "private_network", ip: "192.168.199.10"
      node1.vm.hostname = "hdp-singlenode.example.com"
      node1.vm.provision "shell", inline: "sudo systemctl stop firewalld"
      node1.vm.provision "shell", inline: "sudo systemctl disable firewalld"
      node1.vm.provision "shell", inline: "sudo yum install -y dos2unix"
      node1.vm.provision "shell", inline: "find /usr/src/git_repo/labs/02-Provision_the_environment/Vagrant_single_node/scripts -type f -print0 | xargs -0 dos2unix"
      node1.vm.provision "shell", path: "scripts/install_utilities.sh"
      node1.vm.provision "shell", path: "scripts/setup_mysql.sh"
      node1.vm.provision "shell", path: "scripts/install_ambari_server.sh"
      node1.vm.provision "shell", path: "scripts/install_ambari_agent.sh"
      node1.vm.provision "shell", path: "scripts/link_repo_to_vagrant_user.sh"
      node1.vm.provision "shell", path: "scripts/install_pig_0.17.sh"
      node1.vm.provision "shell", path: "scripts/install_maven.sh"
      node1.vm.provision "shell", path: "scripts/create_cluster.sh"
      #node1.vm.provision "shell", path: "scripts/add_vagrant_user_to_ambari.sh"
      node1.vm.provision "shell", path: "scripts/install_nifi.sh"
      node1.vm.provision "shell", path: "scripts/install_mosquitto.sh"
      node1.vm.network "forwarded_port", guest: 8080, host: 8080
      node1.vm.network "forwarded_port", guest: 8090, host: 8090
      node1.vm.network "forwarded_port", guest: 3306, host: 3306
      node1.vm.network "forwarded_port", guest: 50070, host: 50070
      node1.vm.network "forwarded_port", guest: 8088, host: 8088
      node1.vm.network "forwarded_port", guest: 8020, host: 8020
      node1.vm.provider "virtualbox" do |v|
        #v.memory = 4096
        v.memory = 6144
        v.cpus = 2
        v.customize ['modifyvm', :id, '--cableconnected1', 'on']
        v.name = "hdp_singlenode"
      end
      node1.vm.provider :libvirt do |libvirt|
        libvirt.memory = 12000
      end
    end
  end
